#!/bin/bash
# chkconfig: 2345 20 80
# description: Description comes here....

# Source function library.
#./etc/init.d/functions

   start() {
     ifconfig | ssmtp design3.2013.5@gmail.com
   }

   stop() {
      ifconfig > /home/ifconfig.txt
   }

   case "$1" in 
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
         echo "Usage: $0 {start|stop|restart}"

   esac
   exit 0
